// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBaPfxQxxcUGAAdpLjRdfhWTa7RSCfgD_I',
    appId: '1:39947690164:web:8391f46ba3d2e8a83df7e1',
    messagingSenderId: '39947690164',
    projectId: 'online-books-1c0e0',
    authDomain: 'online-books-1c0e0.firebaseapp.com',
    storageBucket: 'online-books-1c0e0.appspot.com',
    measurementId: 'G-M552DWSNJX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCCZnDxO6TYBTRSKJMahuCd73vw7EFyVxU',
    appId: '1:39947690164:android:07dddcf8fa6b03153df7e1',
    messagingSenderId: '39947690164',
    projectId: 'online-books-1c0e0',
    storageBucket: 'online-books-1c0e0.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBnL1S2kB2kXFLN-EBItmLlQ3O12BkeqjU',
    appId: '1:39947690164:ios:3b20f7d60a1f40713df7e1',
    messagingSenderId: '39947690164',
    projectId: 'online-books-1c0e0',
    storageBucket: 'online-books-1c0e0.appspot.com',
    iosBundleId: 'com.example.flutterFirabaseBookApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBaPfxQxxcUGAAdpLjRdfhWTa7RSCfgD_I',
    appId: '1:39947690164:web:aeee43174e820f973df7e1',
    messagingSenderId: '39947690164',
    projectId: 'online-books-1c0e0',
    authDomain: 'online-books-1c0e0.firebaseapp.com',
    storageBucket: 'online-books-1c0e0.appspot.com',
    measurementId: 'G-F7PH68CKEF',
  );

}